server:
  port: 8080

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/ipam
    username: ipam
    password: ipam

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10s

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health     