version: '3'

services:

  postgres:
    image: postgres:15
    container_name: ipam_postgres
    environment:
      POSTGRES_DB: ipam
      POSTGRES_USER: ipam
      POSTGRES_PASSWORD: ipam
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: ipam_redis
    ports:
      - "6379:6379"